mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-nvidia-h265

record:
  enabled: true
  retain:
    days: 30
    mode: all

detect:
  enabled: true

detectors:
  onnx:
    type: onnx

model:
  model_type: yolox
  width: 768
  height: 1024
  input_tensor: nchw
  input_dtype: float_denorm
  path: /config/model_cache/yolox_tiny.onnx
  labelmap_path: /labelmap/coco-80.txt

snapshots:
  enabled: true
  retain:
    default: 2

go2rtc:
  streams:
    front_gate_main: "rtsp://${FRIGATE_RTSP_USER}:${FRIGATE_RTSP_PASSWORD}@192.168.1.40:554/Preview_01_main"
    front_gate_sub: "rtsp://${FRIGATE_RTSP_USER}:${FRIGATE_RTSP_PASSWORD}@192.168.1.40:554/Preview_01_sub"
    signpost_main: "rtsp://${FRIGATE_RTSP_USER}:${FRIGATE_RTSP_PASSWORD}@192.168.1.31:554/Preview_01_main"
    signpost_sub: "rtsp://${FRIGATE_RTSP_USER}:${FRIGATE_RTSP_PASSWORD}@192.168.1.31:554/Preview_01_sub"

# Requires env vars: FRIGATE_RTSP_USER and FRIGATE_RTSP_PASSWORD
cameras:
  front_gate:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_gate_main
          roles: [record, detect]
    live:
      stream_name: front_gate_sub
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - car

  signpost:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/signpost_main
          roles: [record, detect]
    live:
      stream_name: signpost_sub
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - car

version: 0.16-0

semantic_search:
  enabled: true
  model_size: small

face_recognition:
  enabled: false

lpr:
  enabled: true

classification:
  bird:
    enabled: false
